trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /dependency/main-variable.yaml

pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job: FirstJob
    variables:
     - template: /dependency/variable-template.yaml
    steps:
    - script: echo $(my_var) ${{ variables.var1 }} ${{ variables.var2 }} ${{ variables.var3 }}